# .github/workflows/sync-to-ado.yml
name: Mirror to Azure DevOps

on:
  push:
    branches: [main, develop, feature/**]
    tags:
      - "**"
  delete:
    branches: [main, develop, feature/**]
    tags:
      - "**"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "OrgBorgCorg"
          git config --global user.email "ivanjaison@gmail.com"

      - name: Add ADO Remote
        run: |
          git remote add ado https://:${{ secrets.ADO_PAT }}@dev.azure.com/ivanjmadathil/django-admin-jwt-test/_git/ShellScripts || \
          git remote set-url ado https://:${{ secrets.ADO_PAT }}@dev.azure.com/ivanjmadathil/django-admin-jwt-test/_git/ShellScripts

      - name: Push to ADO
        run: |
          git push ado --all --force
          git push ado --tags --force
